### ISSUE TITLE
Using ussue

### ISSUE THREAD

**Issue by gydronix** [aws/Fleet-Provisioning-for-AWS-IoT-embedded-sdk#14]
Hello,

Is there any example with this library?

**Comment by archigup** [comment]
Hi, thanks for reaching out! We have a demo here: <https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/demos/fleet_provisioning>.

The demo is currently in development, so expect changes until it is released.

**Comment by aggarw13** [comment]
Hi @gydronix, we released the demo of using the Provisioning library in the [202108.00 release](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202108.00) of C-SDK.  You can find the released version of the demo [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202108.00/demos/fleet_provisioning/fleet_provisioning_with_csr).

**Comment by pvyawaha** [comment]
Closing this issue now, please reopen for the same topic or new issue for other topics.
